/*
   Copyright 2016 James Fong

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

*/

#ifndef PGG_NALINPUTS_HPP
#define PGG_NALINPUTS_HPP

#include "SDL2/SDL.h"

namespace pgg {

namespace Input {

enum MouseButton {
    LEFT,
    MIDDLE,
    RIGHT,
    SPECIAL_0,
    SPECIAL_1,
    DEFAULT
};

MouseButton mouseButtonFromSDL(uint8_t button);

enum KeyScancode {
    UNKNOWN,
    NUM_0,
    NUM_1,
    NUM_2,
    NUM_3,
    NUM_4,
    NUM_5,
    NUM_6,
    NUM_7,
    NUM_8,
    NUM_9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    NUMPAD_0,
    NUMPAD_1,
    NUMPAD_2,
    NUMPAD_3,
    NUMPAD_4,
    NUMPAD_5,
    NUMPAD_6,
    NUMPAD_7,
    NUMPAD_8,
    NUMPAD_9,
    NUMPAD_00,
    NUMPAD_000,
    NUMPAD_A,
    NUMPAD_B,
    NUMPAD_C,
    NUMPAD_D,
    NUMPAD_E,
    NUMPAD_F,
    NUMPAD_AMPERSAND,
    NUMPAD_AT,
    NUMPAD_BACKSPACE,
    NUMPAD_BINARY,
    NUMPAD_CLEAR,
    NUMPAD_CLEAR_ENTRY,
    NUMPAD_COLON,
    NUMPAD_COMMA,
    NUMPAD_DOUBLE_AMPERSAND,
    NUMPAD_DOUBLE_VERTICAL,
    NUMPAD_DECIMAL_POINT,
    NUMPAD_DIVIDE,
    NUMPAD_ENTER,
    NUMPAD_EQUALS,
    NUMPAD_EQUALS_ALT,
    NUMPAD_FACTORIAL,
    NUMPAD_GREATER_THAN,
    NUMPAD_HASH,
    NUMPAD_HEX,
    NUMPAD_BRACE_LEFT,
    NUMPAD_PARENTHESIS_LEFT,
    NUMPAD_LESS_THAN,
    NUMPAD_MEMORY_ADD,
    NUMPAD_MEMORY_CLEAR,
    NUMPAD_MEMORY_DIVIDE,
    NUMPAD_MEMORY_MULTIPLY,
    NUMPAD_MEMORY_CALL,
    NUMPAD_MEMORY_STORE,
    NUMPAD_MEMORY_SUBTRACT,
    NUMPAD_SUBTRACT,
    NUMPAD_MULTIPLY,
    NUMPAD_OCT,
    NUMPAD_PERCENT,
    NUMPAD_PERIOD,
    NUMPAD_ADD,
    NUMPAD_PLUS_MINUS,
    NUMPAD_CARET,
    NUMPAD_BRACE_RIGHT,
    NUMPAD_PARENTHESIS_RIGHT,
    NUMPAD_SPACE,
    NUMPAD_TAB,
    NUMPAD_VERTICAL,
    NUMPAD_XOR,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    APP_BACK,
    APP_FAVORITES,
    APP_FORWARD,
    APP_HOME,
    APP_REFRESH,
    APP_SEARCH,
    APP_STOP,
    REDO,
    ERASE,
    APOSTROPHE,
    APP_MENU,
    SND_MUTE,
    SND_NEXT,
    SND_PLAY,
    SND_PREV,
    SND_STOP,
    BACKSLASH,
    BACKSPACE,
    BRIGHTNESS_DOWN,
    BRIGHTNESS_UP,
    CALCULATOR,
    CANCEL,
    CAPS_LOCK,
    CLEAR,
    CLEAR_AGAIN,
    COMMA,
    MY_COMPUTER,
    COPY,
    CR_CEL,
    CURRENCY_SUB_UNIT,
    CURRENCY_UNIT,
    CUT,
    DECIMAL_POINT,
    DELETE,
    VIDEO_MODE_SWITCH,
    ARROW_DOWN,
    EJECT,
    END,
    EQUALS,
    ESCAPE,
    EXECUTE,
    EX_SEL,
    FIND,
    GRAVE,
    HELP,
    HOME,
    INSERT,
    INTERNATIONAL_1,
    INTERNATIONAL_2,
    INTERNATIONAL_3,
    INTERNATIONAL_4,
    INTERNATIONAL_5,
    INTERNATIONAL_6,
    INTERNATIONAL_7,
    INTERNATIONAL_8,
    INTERNATIONAL_9,
    ILLUMINATION_DOWN,
    ILLUMINATION_TOGGLE,
    ILLUMINATION_UP,
    ALT_LEFT,
    LANG_1,
    LANG_2,
    LANG_3,
    LANG_4,
    LANG_5,
    LANG_6,
    LANG_7,
    LANG_8,
    LANG_9,
    CONTROL_LEFT,
    ARROW_LEFT,
    BRACKET_LEFT,
    GUI_LEFT,
    SHIFT_LEFT,
    MAIL,
    MEDIA_SELECT,
    MENU,
    SUBTRACT,
    MODE_SWITCH,
    MUTE,
    NUMLOCK,
    OPER,
    OUT,
    PAGE_DOWN,
    PAGE_UP,
    PASTE,
    PAUSE,
    PERIOD,
    POWER,
    PRINTSCREEN,
    PRIOR,
    ALT_RIGHT,
    CONTROL_RIGHT,
    RETURN,
    RETURN_ALT,
    GUI_RIGHT,
    ARROW_RIGHT,
    BRACKET_RIGHT,
    SHIFT_RIGHT,
    SCROLL_LOCK,
    SELECT,
    SEMICOLON,
    SEPARATOR,
    SLASH,
    SLEEP,
    SPACEBAR,
    STOP,
    SYS_REQ,
    TAB,
    THOUSANDS_SEPARATOR,
    UNDO,
    ARROW_UP,
    SND_VOLUME_DOWN,
    SND_VOLUME_UP,
    WORLD_WIDE_WEB,
    
    ENUM_SIZE
};

KeyScancode keyScancodeFromSDL(SDL_Scancode key);

}

}

#endif // PGG_NALINPUTS_HPP
